<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.2" name="minirogue-all" tilewidth="8" tileheight="8" tilecount="208" columns="16">
 <editorsettings>
  <export target="minirogue-all.tsj" format="json"/>
 </editorsettings>
 <image source="minirogue-all.png" width="128" height="104"/>
 <tile id="0" type="empty"/>
 <tile id="1" type="floor_1"/>
 <tile id="2" type="floor_2"/>
 <tile id="3" type="wall"/>
 <tile id="4" type="stair_up"/>
 <tile id="5" type="stair_down"/>
 <tile id="9" type="grass_1"/>
 <tile id="10" type="grass_2"/>
 <tile id="11" type="grass_3"/>
 <tile id="12" type="grass_4"/>
 <tile id="13" type="plant"/>
 <tile id="14" type="tree_1"/>
 <tile id="15" type="tree_2"/>
 <tile id="16" type="path_1"/>
 <tile id="17" type="path_2"/>
 <tile id="21" type="lillypad"/>
 <tile id="22" type="bones_1"/>
 <tile id="23" type="bones_2"/>
 <tile id="24" type="bones_3"/>
 <tile id="25" type="bones_4"/>
 <tile id="26" type="rocks"/>
 <tile id="27" type="door_1"/>
 <tile id="28" type="door_2"/>
 <tile id="29" type="door_3"/>
 <tile id="30" type="door_4"/>
 <tile id="31" type="doot_5"/>
 <tile id="32" type="chest_gold_closed"/>
 <tile id="33" type="chest_gold_open"/>
 <tile id="34" type="silver_chest_closed"/>
 <tile id="35" type="silver_chest_open"/>
 <tile id="36" type="coins"/>
 <tile id="37" type="necklace"/>
 <tile id="38" type="diamond"/>
 <tile id="39" type="ring_1"/>
 <tile id="40" type="ring_2"/>
 <tile id="41" type="key_1"/>
 <tile id="42" type="key_2"/>
 <tile id="43" type="key_3"/>
 <tile id="44" type="key_4"/>
 <tile id="45" type="key_5"/>
 <tile id="46" type="key_6"/>
 <tile id="47" type="apple"/>
 <tile id="48" type="mushroom"/>
 <tile id="49" type="meat"/>
 <tile id="50" type="fish"/>
 <tile id="51" type="flowers"/>
 <tile id="52" type="red_potion"/>
 <tile id="53" type="blue_potion"/>
 <tile id="54" type="black_potion"/>
 <tile id="55" type="green_potion"/>
 <tile id="56" type="amber_potion"/>
 <tile id="58" type="book"/>
 <tile id="63" type="scimitar"/>
 <tile id="64" type="dagger"/>
 <tile id="65" type="sword"/>
 <tile id="66" type="battleaxe"/>
 <tile id="67" type="crossbwo"/>
 <tile id="68" type="bolt"/>
 <tile id="69" type="bow"/>
 <tile id="70" type="arrow"/>
 <tile id="71" type="axe"/>
 <tile id="75" type="small_helm"/>
 <tile id="76" type="med_helm"/>
 <tile id="77" type="full_helm"/>
 <tile id="79" type="boot_1"/>
 <tile id="80" type="boot_2"/>
 <tile id="81" type="cloak"/>
 <tile id="85" type="character_1"/>
 <tile id="86" type="character_2"/>
 <tile id="87" type="character_3"/>
 <tile id="88" type="undead_1"/>
 <tile id="89" type="bearded_character"/>
 <tile id="90" type="wizard_1"/>
 <tile id="91" type="wizard_2"/>
 <tile id="92" type="cloaked_guy"/>
 <tile id="93" type="vampire"/>
 <tile id="94" type="merman"/>
 <tile id="95" type="goose"/>
 <tile id="96" type="cat_person"/>
 <tile id="97" type="zombie"/>
 <tile id="98" type="tree_guy"/>
 <tile id="99" type="bat"/>
 <tile id="103" type="squid_1"/>
 <tile id="104" type="squid_2"/>
 <tile id="105" type="skeleton"/>
 <tile id="106" type="cloaked_skeleton"/>
 <tile id="107" type="snake_1"/>
 <tile id="108" type="snake_2"/>
 <tile id="109" type="snake_3"/>
 <tile id="110" type="rat_1"/>
 <tile id="111" type="rat_2"/>
 <tile id="112" type="flying_1"/>
 <tile id="113" type="flying_2"/>
 <tile id="114" type="ghost"/>
 <tile id="115" type="cat"/>
 <tile id="116" type="giant_cobra"/>
 <tile id="117" type="giant_cobra"/>
 <tile id="118" type="big_tree"/>
 <tile id="119" type="big_tree"/>
 <tile id="120" type="giant_ghost"/>
 <tile id="121" type="giant_ghost"/>
 <tile id="122" type="giant_colossus"/>
 <tile id="123" type="giant_colossus"/>
 <tile id="124" type="dragon"/>
 <tile id="125" type="dragon"/>
 <tile id="126" type="giant_demon"/>
 <tile id="127" type="giant_demon"/>
 <tile id="128" type="giant_spider"/>
 <tile id="129" type="giant_spider"/>
 <tile id="130" type="giant_skeleton"/>
 <tile id="131" type="giant_skeleton"/>
 <tile id="132" type="giant_cobra"/>
 <tile id="133" type="giant_cobra"/>
 <tile id="134" type="big_tree"/>
 <tile id="135" type="big_tree"/>
 <tile id="136" type="giant_ghost"/>
 <tile id="137" type="giant_ghost"/>
 <tile id="138" type="giant_colossus"/>
 <tile id="139" type="giant_colossus"/>
 <tile id="140" type="dragon"/>
 <tile id="141" type="dragon"/>
 <tile id="142" type="giant_demon"/>
 <tile id="143" type="giant_demon"/>
 <tile id="144" type="giant_spider"/>
 <tile id="145" type="giant_spider"/>
 <tile id="146" type="giant_skeleton"/>
 <tile id="147" type="giant_skeleton"/>
 <tile id="148" type="skull"/>
 <tile id="151" type="full_heart"/>
 <tile id="152" type="empty_heart"/>
 <tile id="153" type="ui_bottomleft_edge"/>
 <tile id="154" type="ui_bottom_edge"/>
 <tile id="155" type="ui_bottomright_edge"/>
 <tile id="156" type="ui_side_edge"/>
 <tile id="157" type="ui_topright_edge"/>
 <tile id="164" type="multieyed_demon"/>
 <tile id="165" type="multieyed_demon"/>
 <tile id="170" type="undead_dragon"/>
 <tile id="171" type="undead_dragon"/>
 <tile id="172" type="ui_topleft_edge"/>
 <tile id="180" type="multieyed_demon"/>
 <tile id="181" type="multieyed_demon"/>
 <tile id="186" type="undead_dragon"/>
 <tile id="187" type="undead_dragon"/>
</tileset>
